FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /server
WORKDIR /server
COPY requirements.txt /server/
EXPOSE 8000
RUN pip install -r requirements.txt
COPY . /server/
RUN python manage.py makemigrations
RUN python manage.py migrate